export Landing from './landingView/Landing'
export Header from './app/Header'
export Footer from './app/Footer'
export Shop from './searchResultsView/Shop'
export ShopsList from './searchResultsView/ShopsList'
export Map from './searchResultsView/Map'
export MapBox from './searchResultsView/MapBox'
export CoffeeRunForm from './coffeeRunView/CoffeeRunForm'
